import { Suspense } from 'react'
import ThemeRegistry from './ThemeRegistry'
import Loading from './loading'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout(props: {
  children: React.ReactNode
  results: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body style={{ minHeight: '100vh' }}>
        <ThemeRegistry>
          <Suspense fallback={<Loading />}>
            <>
              {props.children}
              {props.results}
            </>
          </Suspense>
        </ThemeRegistry>
      </body>
    </html>
  )
}
