import ThemeRegistry from './ThemeRegistry'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout(props: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body style={{ minHeight: '100vh' }}>
        <ThemeRegistry>{props.children}</ThemeRegistry>
      </body>
    </html>
  )
}
