import { Suspense } from 'react'
import ThemeRegistry from './ThemeRegistry'
import Loading from './loading'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  message,
}: {
  children: React.ReactNode
  message: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body style={{ minHeight: '100vh' }}>
        <ThemeRegistry>
          <Suspense
            fallback={
              <>
                <Loading /> {message}{' '}
              </>
            }
          >
            {message}
            {children}
          </Suspense>
        </ThemeRegistry>
      </body>
    </html>
  )
}
